import{a as f,S as y,i as c}from"./assets/vendor-ee72e1a4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const h of s.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&n(h)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();const L="https://pixabay.com/api/",v="45091921-bafbe55c990439d7032dec8c8",x=15,w=20;async function p(r,t){try{return(await f.get(L,{params:{key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,_limit:w,per_page:x}})).data}catch(a){throw console.error(a),new Error("Failed to fetch data")}}function u(r){const t=new y(".gallery-list a",{captions:!0,captionsData:"alt",captionsDelay:250}),a=document.querySelector(".gallery-list");let n=r.hits.map(e=>`<div class="image-wrapper">
    <a href="${e.largeImageURL}">
    <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}"></img>
    </a>
    <div class="text-wrapper">
    <div class="text-item"><h5 class="text-header">Likes</h5><p class="text-paragraph">${e.likes}</p></div>
    <div class="text-item"><h5 class="text-header">Views</h5><p class="text-paragraph">${e.views}</p></div>
    <div class="text-item"><h5 class="text-header">Comments</h5><p class="text-paragraph">${e.comments}</p></div>
    <div class="text-item"><h5 class="text-header">Downloads</h5><p class="text-paragraph">${e.downloads}</p></div>
    </div>
    </div>`).join("");a.insertAdjacentHTML("beforeend",n),t.refresh()}function b(){const r=document.querySelector(".gallery-list");r.innerHTML=""}const m=document.querySelector(".form-gallery"),S=document.querySelector(".form-gallery-input"),d=document.querySelector(".loader"),o=document.querySelector(".load-more");let l="",i=1,g=0;m.addEventListener("submit",q);o.addEventListener("click",P);async function q(r){r.preventDefault(),b(),o.classList.add("hidden"),d.classList.remove("hidden"),l=S.value.trim(),i=1;try{const t=await p(l,i);t.total===0||l===""?c.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}):(u(t),g=t.totalHits,t.hits.length>0&&o.classList.remove("hidden"))}catch{c.error({position:"topRight",message:"Error fetching images. Please try again later."})}finally{d.classList.add("hidden")}m.reset()}async function P(){i+=1,d.classList.remove("hidden"),o.classList.add("hidden");try{const r=await p(l,i);u(r),i*15>=g?(o.classList.add("hidden"),c.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})):o.classList.remove("hidden");const{height:t}=document.querySelector(".gallery-list").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch{c.error({position:"topRight",message:"Error loading more images. Please try again later."})}finally{d.classList.add("hidden")}}
//# sourceMappingURL=commonHelpers.js.map
